name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: "\U0001F680 Features"
    labels:
      - 'feature'
      - 'enhancement'
  - title: "\U0001F41B Bug Fixes"
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: "\U0001F9F0 Maintenance"
    labels:
      - 'chore'
      - 'dependencies'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES
