name: Deploy to WordPress.org

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to WordPress.org
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://wordpress.org/plugins/anyway-feedback/
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: composer

      - name: Setup Node.JS
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'

      - name: Install dependencies and build Assets
        run: |
          composer install --no-dev --prefer-dist
          npm ci --ignore-scripts
          npm run package

      - name: Generate readme.txt
        uses: tarosky/workflows/actions/wp-readme@main

      - name: Versioning
        uses: tarosky/workflows/actions/versioning@main
        with:
          version: ${{ github.event.release.tag_name }}
          files: readme.txt,anyway-feedback.php

      - name: Deploy to WordPress Directory
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
        env:
          SLUG: anyway-feedback
          SVN_USERNAME: ${{ secrets.WP_ORG_USERNAME }}
          SVN_PASSWORD: ${{ secrets.WP_ORG_PASSWORD }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/${{ github.event.repository.name }}.zip
